# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name=b'Nombre')),
                ('id_mapa', models.CharField(max_length=255, unique=True, verbose_name=b'Id mapa')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name=b'Slug')),
                ('titulo', models.CharField(blank=True, max_length=255, verbose_name='T\xedtulo')),
                ('fuente', models.TextField(blank=True, max_length=1000, verbose_name='Fuente')),
                ('contacto', models.TextField(blank=True, max_length=1000, verbose_name='Contacto')),
                ('descripcion', models.TextField(blank=True, max_length=10000, verbose_name='Descripci\xf3n')),
                ('srs', models.CharField(blank=True, max_length=100, verbose_name=b'SRS')),
                ('tipo_de_mapa', models.CharField(blank=True, choices=[(b'', b''), (b'layer', b'layer'), (b'layer_original_srs', b'layer_original_srs'), (b'user', b'user'), (b'public_layers', b'public_layers'), (b'general', b'general')], default=b'', max_length=30, verbose_name=b'Tipo de Mapa')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name=b'Size')),
                ('extent', models.CharField(blank=True, max_length=100, verbose_name=b'Extent')),
                ('imagecolor', models.CharField(blank=True, max_length=100, verbose_name=b'Imagecolor')),
                ('imagetype', models.CharField(blank=True, max_length=100, verbose_name=b'Imagetype')),
                ('publico', models.BooleanField(default=False, verbose_name='P\xfablico?')),
                ('palabras_claves', models.TextField(blank=True, default=b'', max_length=10000, verbose_name='Palabras Claves')),
                ('texto_output', models.TextField(blank=True, max_length=10000, verbose_name='Texto Output')),
                ('timestamp_alta', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de alta')),
                ('timestamp_modificacion', models.DateTimeField(auto_now=True, verbose_name=b'Fecha de \xc3\xbaltima modificaci\xc3\xb3n')),
                ('input_search_index', models.TextField(blank=True, default=b'')),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default=b'', editable=False, null=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
            },
        ),
        migrations.CreateModel(
            name='MapServerLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_de_capa', models.IntegerField()),
                ('feature_info', models.BooleanField(default=True, verbose_name='Feature Info')),
                ('texto_input', models.TextField(blank=True, max_length=10000, verbose_name='Texto Input')),
                ('texto_output', models.TextField(blank=True, max_length=10000, verbose_name='Texto Output')),
                ('archivo_sld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.ArchivoSLD')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Mapa')),
            ],
            options={
                'verbose_name': 'MapServer Layer',
                'verbose_name_plural': 'MapServer Layers',
            },
        ),
        migrations.CreateModel(
            name='TMSBaseLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name=b'Nombre')),
                ('url', models.CharField(max_length=2000, verbose_name=b'URL')),
                ('min_zoom', models.IntegerField(blank=True, null=True, verbose_name=b'Min zoom')),
                ('max_zoom', models.IntegerField(blank=True, null=True, verbose_name=b'Max zoom')),
                ('tms', models.BooleanField(default=True, verbose_name='TMS?')),
                ('fuente', models.CharField(blank=True, max_length=255, verbose_name=b'Fuente')),
                ('descripcion', models.TextField(blank=True, max_length=10000, verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'TMS Base Layer',
                'verbose_name_plural': 'TMS Base Layers',
            },
        ),
        migrations.AddField(
            model_name='mapa',
            name='capas',
            field=models.ManyToManyField(blank=True, null=True, through='maps.MapServerLayer', to='layers.Capa'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, to='layers.Categoria', verbose_name='Categor\xedas'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='escala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Escala'),
        ),
        migrations.AddField(
            model_name='mapa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mapa',
            name='tms_base_layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maps.TMSBaseLayer', verbose_name=b'Capa Base'),
        ),
    ]
