# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20180620_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='timestamp_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de \xfaltima modificaci\xf3n'),
        ),
    ]
