# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20180620_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='timestamp_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name=b'Fecha de \xc3\xbaltima modificaci\xc3\xb3n'),
        ),
    ]
