# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20181015_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapa',
            name='srs',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'SRS'),
        ),
    ]
