# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatos',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='layers.Categoria', verbose_name='Categor\xedas'),
        ),
    ]
