# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_capa_layer_srs_extent'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='nombre_del_archivo',
            field=models.CharField(default=True, max_length=255, null=True, verbose_name='Nombre del archivo'),
        ),
        migrations.AddField(
            model_name='capa',
            name='tipo_de_capa',
            field=models.CharField(choices=[('vector', 'vector'), ('raster', 'raster')], default='vector', max_length=10, verbose_name='Tipo de capa'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='campo_geom',
            field=models.CharField(blank=True, default='geom', max_length=30, null=True, verbose_name='Campo de Geometr\xeda'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='esquema',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Esquema'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='tabla',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla'),
        ),
        migrations.AlterField(
            model_name='capa',
            name='tipo_de_geometria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.TipoDeGeometria'),
        ),
        migrations.AlterUniqueTogether(
            name='capa',
            unique_together=set([]),
        ),
    ]
