# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20180807_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capa',
            name='tipo_de_geometria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.TipoDeGeometria'),
        ),
    ]
