# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-23 21:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_auto_20180811_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='capa',
            name='cantidad_de_bandas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='gdal_driver_longname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Driver - Long Name'),
        ),
        migrations.AddField(
            model_name='capa',
            name='gdal_driver_shortname',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Driver - Short Name'),
        ),
        migrations.AddField(
            model_name='capa',
            name='gdal_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='capa',
            name='proyeccion_proj4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='capa',
            name='size_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capa',
            name='size_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
