# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-02 22:39
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0007_auto_20180923_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyeccion_proj4', models.CharField(blank=True, default='', max_length=255)),
                ('srid', models.IntegerField(verbose_name='SRID')),
                ('extent', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('timestamp_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de \xfaltima modificaci\xf3n')),
                ('nombre_del_archivo', models.CharField(max_length=255, verbose_name='Nombre del archivo')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicaci\xf3n del archivo')),
                ('gdal_driver_shortname', models.CharField(blank=True, default='', max_length=100, verbose_name='Driver - Short Name')),
                ('gdal_driver_longname', models.CharField(blank=True, default='', max_length=100, verbose_name='Driver - Long Name')),
                ('gdal_metadata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('cantidad_de_bandas', models.IntegerField(blank=True, null=True)),
                ('size_height', models.IntegerField(blank=True, null=True)),
                ('size_width', models.IntegerField(blank=True, null=True)),
                ('data_datetime', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers_rasterdatasource_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VectorDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyeccion_proj4', models.CharField(blank=True, default='', max_length=255)),
                ('srid', models.IntegerField(verbose_name='SRID')),
                ('extent', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('timestamp_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de \xfaltima modificaci\xf3n')),
                ('esquema', models.CharField(blank=True, max_length=100, null=True, verbose_name='Esquema')),
                ('tabla', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla')),
                ('campo_geom', models.CharField(blank=True, default='geom', max_length=30, null=True, verbose_name='Campo de Geometr\xeda')),
                ('cantidad_de_registros', models.IntegerField(blank=True, null=True, verbose_name='Cantidad de registros')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa')),
                ('conexion_postgres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.ConexionPostgres')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers_vectordatasource_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
