# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0008_rasterdatasource_vectordatasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdatasource',
            name='timestamp_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de \xfaltima modificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vectordatasource',
            name='timestamp_modificacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de \xfaltima modificaci\xf3n'),
        ),
    ]
