# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0009_auto_20190115_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='vectordatasource',
            name='data_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rasterdatasource',
            name='timestamp_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de \xfaltima modificaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='vectordatasource',
            name='timestamp_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de \xfaltima modificaci\xf3n'),
        ),
    ]
