# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import layers.models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0010_auto_20190115_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosld',
            name='filename',
            field=models.FileField(max_length=500, upload_to=layers.models.get_sld_filename, verbose_name='Nombre de archivo SLD'),
        ),
    ]
