# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0011_auto_20190120_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdatasource',
            name='data_datetime',
            field=models.DateTimeField(verbose_name='Fecha de los datos'),
        ),
    ]
