# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-25 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0012_auto_20190122_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectordatasource',
            name='data_datetime',
            field=models.DateTimeField(verbose_name='Fecha de los datos'),
        ),
    ]
