# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-24 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0013_auto_20190124_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasterdatasource',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasterdatasources', to='layers.Capa'),
        ),
        migrations.AlterField(
            model_name='vectordatasource',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectordatasources', to='layers.Capa'),
        ),
    ]
