# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 03:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoDeCapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[(b'read', b'read'), (b'write', b'write')], max_length=10, verbose_name=b'Permiso')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usuario')),
            ],
            options={
                'ordering': ['user__username'],
                'verbose_name': 'Permiso de Capa',
                'verbose_name_plural': 'Permisos de Capas',
            },
        ),
        migrations.CreateModel(
            name='PermisoDeCapaPorGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[(b'read', b'read'), (b'write', b'write')], max_length=10, verbose_name=b'Permiso')),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name=b'Grupo')),
            ],
            options={
                'ordering': ['group__name'],
                'verbose_name': 'Permiso de Capa por Grupo',
                'verbose_name_plural': 'Permisos de Capas por Grupos',
            },
        ),
        migrations.CreateModel(
            name='PermisoDeMapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.CharField(choices=[(b'read', b'read'), (b'write', b'write')], max_length=10, verbose_name=b'Permiso')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Mapa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Usuario')),
            ],
            options={
                'verbose_name': 'Permiso de Mapa',
                'verbose_name_plural': 'Permisos de Mapas',
            },
        ),
        migrations.AlterUniqueTogether(
            name='permisodemapa',
            unique_together=set([('user', 'mapa')]),
        ),
        migrations.AlterUniqueTogether(
            name='permisodecapaporgrupo',
            unique_together=set([('group', 'capa')]),
        ),
        migrations.AlterUniqueTogether(
            name='permisodecapa',
            unique_together=set([('user', 'capa')]),
        ),
    ]
