# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20180706_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
