# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-11 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('layerimport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoRaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('path_del_archivo', models.CharField(max_length=255, unique=True, verbose_name='Path absoluto del Archivo')),
                ('formato', models.CharField(max_length=255)),
                ('cantidad_de_bandas', models.IntegerField(blank=True, null=True)),
                ('srid', models.IntegerField(default=4326)),
                ('extent', models.CharField(default='', max_length=255)),
                ('heigth', models.IntegerField()),
                ('width', models.IntegerField()),
                ('timestamp_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layerimport_archivoraster_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Archivo Raster',
                'verbose_name_plural': 'Archivos Rasters',
            },
        ),
        migrations.AlterUniqueTogether(
            name='archivoraster',
            unique_together=set([('owner', 'nombre_del_archivo')]),
        ),
    ]
