# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layerimport', '0002_auto_20180811_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablageografica',
            options={'verbose_name': 'Tabla Geogr\xe1fica', 'verbose_name_plural': 'Tablas Geogr\xe1ficas'},
        ),
    ]
