# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 03:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields
import layers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoSLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo_sld', models.CharField(max_length=500, unique=True, verbose_name=b'Id Archivo SLD')),
                ('filename', models.FileField(max_length=500, upload_to=layers.models.get_sld_filename, verbose_name=b'Nombre de Archivo')),
                ('descripcion', models.TextField(blank=True, max_length=10000, verbose_name='Descripci\xf3n')),
                ('default', models.BooleanField(default=False, verbose_name='Activa')),
                ('user_alta', models.CharField(blank=True, default=b'', max_length=50, verbose_name='Subido por')),
                ('user_modificacion', models.CharField(blank=True, default=b'', max_length=50, verbose_name='Modificado por')),
                ('timestamp_alta', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha de alta')),
                ('timestamp_modificacion', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha de \xc3\xbaltima modificaci\xc3\xb3n')),
            ],
            options={
                'verbose_name': 'Archivo SLD',
                'verbose_name_plural': 'Archivos SLD',
            },
        ),
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name=b'Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=255, verbose_name='Descripci\xf3n')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': '\xc1rea Tem\xe1tica',
                'verbose_name_plural': '\xc1reas Tem\xe1ticas',
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_campo', models.CharField(max_length=50, verbose_name=b'Nombre del Campo')),
                ('tipo', models.CharField(blank=True, max_length=50, verbose_name=b'Tipo')),
                ('alias', models.CharField(blank=True, max_length=50, verbose_name=b'Alias')),
                ('descripcion', models.TextField(blank=True, max_length=1000, verbose_name='Descripci\xf3n')),
                ('publicable', models.BooleanField(default=True)),
                ('unico', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name=b'Nombre')),
                ('id_capa', models.CharField(max_length=255, unique=True, verbose_name=b'Id capa')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name=b'Slug')),
                ('campo_geom', models.CharField(default=b'geom', max_length=30, verbose_name='Campo de Geometr\xeda')),
                ('esquema', models.CharField(max_length=100, verbose_name=b'Esquema')),
                ('tabla', models.CharField(max_length=100, verbose_name=b'Tabla')),
                ('wxs_publico', models.BooleanField(default=False, verbose_name='WMS/WFS P\xfablico?')),
                ('cantidad_de_registros', models.IntegerField(blank=True, null=True, verbose_name=b'Cantidad de registros')),
                ('srid', models.IntegerField(verbose_name=b'SRID')),
                ('extent_minx_miny', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='(Minx, Miny)')),
                ('extent_maxx_maxy', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='(Maxx, Maxy)')),
                ('timestamp_alta', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de alta')),
                ('timestamp_modificacion', models.DateTimeField(auto_now=True, verbose_name=b'Fecha de \xc3\xbaltima modificaci\xc3\xb3n')),
            ],
            options={
                'verbose_name': 'Capa',
                'verbose_name_plural': 'Capas',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name=b'Nombre')),
                ('descripcion', models.TextField(blank=True, max_length=255, verbose_name='Descripci\xf3n')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Categor\xeda',
                'verbose_name_plural': 'Categor\xedas',
            },
        ),
        migrations.CreateModel(
            name='ConexionPostgres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, verbose_name=b'Nombre')),
                ('host', models.CharField(max_length=50, verbose_name=b'Host')),
                ('port', models.CharField(blank=True, max_length=50, verbose_name=b'Port')),
                ('dbname', models.CharField(max_length=50, verbose_name=b'Database')),
                ('user', models.CharField(max_length=50, verbose_name=b'User')),
                ('password', models.CharField(max_length=50, verbose_name=b'Password')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Conexi\xf3n Postgres',
                'verbose_name_plural': 'Conexiones Postgres',
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name=b'Nombre')),
            ],
            options={
                'ordering': ['nombre'],
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='Metadatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_capa', models.CharField(blank=True, max_length=255, verbose_name=b'Nombre Capa')),
                ('slug_capa', models.CharField(blank=True, max_length=255, verbose_name=b'Slug Capa')),
                ('titulo', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('fuente', models.TextField(blank=True, max_length=1000, verbose_name='Fuente')),
                ('contacto', models.TextField(blank=True, max_length=1000, verbose_name='Contacto')),
                ('descripcion', models.TextField(blank=True, max_length=10000, verbose_name='Descripci\xf3n')),
                ('palabras_claves', models.TextField(blank=True, max_length=10000, verbose_name='Palabras Claves')),
                ('fecha_de_relevamiento', models.CharField(blank=True, max_length=50, verbose_name=b'Fecha de Relevamiento')),
                ('fecha_de_actualizacion', models.CharField(blank=True, max_length=50, verbose_name='Fecha de Actualizaci\xf3n')),
                ('frecuencia_de_actualizacion', models.CharField(blank=True, max_length=100, verbose_name='Frecuencia de Actualizaci\xf3n')),
                ('timestamp_alta', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha de alta')),
                ('timestamp_modificacion', models.DateTimeField(auto_now=True, verbose_name=b'Fecha de \xc3\xbaltima modificaci\xc3\xb3n')),
                ('input_search_index', models.TextField(blank=True, default=b'')),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default=b'', editable=False, null=True, serialize=False)),
                ('area_tematica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.AreaTematica', verbose_name='\xc1rea Tem\xe1tica')),
                ('capa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa')),
                ('categorias', models.ManyToManyField(blank=True, null=True, to='layers.Categoria', verbose_name='Categor\xedas')),
                ('escala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='layers.Escala')),
            ],
            options={
                'verbose_name': 'Metadatos de Capa',
                'verbose_name_plural': 'Metadatos de Capas',
            },
        ),
        migrations.CreateModel(
            name='TipoDeGeometria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name=b'Nombre')),
                ('postgres_type', models.CharField(max_length=100, verbose_name='Postgres Type')),
                ('mapserver_type', models.CharField(max_length=50, verbose_name='Mapserver Type')),
            ],
            options={
                'verbose_name': 'Tipo de Geometr\xeda',
                'verbose_name_plural': 'Tipos de Geometr\xeda',
            },
        ),
        migrations.AddField(
            model_name='capa',
            name='conexion_postgres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.ConexionPostgres'),
        ),
        migrations.AddField(
            model_name='capa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers_capa_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='capa',
            name='tipo_de_geometria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.TipoDeGeometria'),
        ),
        migrations.AddField(
            model_name='atributo',
            name='metadatos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Metadatos'),
        ),
        migrations.AddField(
            model_name='archivosld',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Capa'),
        ),
        migrations.AlterUniqueTogether(
            name='capa',
            unique_together=set([('esquema', 'tabla')]),
        ),
        migrations.AlterUniqueTogether(
            name='atributo',
            unique_together=set([('nombre_del_campo', 'metadatos')]),
        ),
    ]
